# Generated by Django 5.1.1 on 2024-10-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='city_id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('sunday', models.IntegerField(verbose_name='sunday')),
                ('monday', models.IntegerField(verbose_name='monday')),
                ('tuesday', models.IntegerField(verbose_name='tuesday')),
                ('wednesday', models.IntegerField(verbose_name='wednesday')),
                ('thursday', models.IntegerField(verbose_name='thursday')),
                ('friday', models.IntegerField(verbose_name='friday')),
                ('saturday', models.IntegerField(verbose_name='saturday')),
            ],
        ),
    ]
