# Generated by Django 5.1.1 on 2024-10-02 05:07
from django.core.management import call_command
from django.db import migrations


def mig(apps, schema_editor):
    call_command("loaddata", "app/initialdata.json", app_label="app")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(mig)]
